name: Publish Docker image
on:
  push:
    branches: [ master ]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Use Node.js 
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm ci
        working-directory: ./app
      - run: npm run build -D --if-present
        working-directory: ./app
      - run: npm test
        working-directory: ./app
      - name: Login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: itasahobby/sampleapp:latest